### PR TITLE
First attempt at generating an interface for the USB-1608G module.

### PR DESCRIPTION
**Pull request by David-Dudley**
Very beginner at this.... don't be too harsh.

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
@David-Dudley you have closed this PR, so I cannot merge it.  But I can comment on it.

- The changes to st.cmd are not needed.  You really only need the one change for the UNIQUE_ID but there is no reason to push that back to master, it can just be a local change on your system.  You should undo all of the changes, commit, and then change the UNIQUE_ID.
- I don't understand why you moved line 47 in LinuxDrivers/Makefile out of the ifeq block.  It should not be built if HAVE_HIDAPI is not YES.
- You should revert USB1608G_NGAINS_1608G back to NGAINS_1608G.  Same for NCHAN_AO_1608GX.  They are already unique to the USB-1608G, there is no need for an additional prefix.
- Please don't change the braces to begin on the next line, it introduces cosmetic changes that make it hard to find what has really changed (line 533, 556, 564, etc.) in usb-1608G.c.  This is particularly true since this is Warren's code and we will want to feed it back to him.
- cbw_linux.cpp line 126 you added trailing whitespace.
- You edited opi/autoconvert/USB1608G_2A0_module.opi.  That is a file that is generated automatically from the medm adl file, and should not be manually edited.
- It looks like mcBoard_USB-1608G.h and .cpp may have tab characters in them.  Please replace all tabs with spaces.

**Comment by David-Dudley** [comment]
See… beginner.

Bullet 2:  usb1608G does not use the HIDAPI functions.  It works directly with libusb.

I’ll work on the other changes tomorrow.

So, I don’t close the PR?

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Comment by MarkRivers** [comment]
> Bullet 2:  usb1608G does not use the HIDAPI functions.  It works directly with libusb.

Sorry,  my mistake.

> So, I don’t close the PR?

No, you leave the PR open.  While we are reviewing/modifying you can continue to push to your fork and those changes will show up in the PR.

It's also better to communicate by using the messages boxes here in the PR on Github rather than by e-mail, since e-mail adds a bunch of extra stuff at the end of the message.

**Comment by David-Dudley** [comment]
One of the things I need to do is to add the new usb driver to this package (something I forgot to do… Warren created the analog output write routine that I need).
Can I pull specific files from his release into this, or do I just checkout his repo and copy the individual files?  Seems the 2nd is wrong, but don’t know if I can pull individual files from another repo into this one???

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Comment by MarkRivers** [comment]
> Can I pull specific files from his release into this, or do I just checkout his repo and copy the individual files?  Seems the 2nd is wrong, but don’t know if I can pull individual files from another repo into this one???

You need to do the latter.  We often need to modify Warren's files.  We try to feed those changes back to him, but we may have local differences.

**Comment by David-Dudley** [comment]
Was afraid that would be the case.

I’ll try to do better tomorrow.

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Comment by David-Dudley** [comment]
Last question… then I won’t bother you for a while.

Is there a way I can remove my pull request from measComp so I can start over?

If I delete the repository, will that remove the pull request?

Alternately, is there a way to reopen it or cancel it?

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Comment by MarkRivers** [comment]
You can simply close the pull request.
I am not sure what you mean by "start over"?  You can do the following:
- Remove your fork on Github
- Fork again
- Clone your fork into a new working directory.  Then you will have the current master branch from epics-modules.  
- Copy only the files you want to change from your old working directory to the new one.  
- Commit and push to your fork
- Make a new pull request

There is a somewhat more elegant way, which is to make a new branch and remote in your current working directory which points to the  epics-modules/measComp.  Then you can copy from that branch to your current branch.  But I think it may be more complicated to understand for someone new to Git.

**Comment by MarkRivers** [comment]
I should say that you don't currently have an open PR, so you don't need to close it.

It's better to have this conversation directly here: https://github.com/epics-modules/measComp/pull/9 than using e-mail.

**Comment by David-Dudley** [comment]
Will deleting my fork remove the update I pushed?  Since it's substantially wrong, I think it would be easier to just start over from the beginning.  There aren't that many files that have changed.

**Comment by David-Dudley** [comment]
I mean "pulled"?

**Comment by David-Dudley** [comment]
I'm an old CVS person.  GIT for the most part is a mystery to me

**Comment by MarkRivers** [comment]
Yes, deleting your fork, creating a new one, and cloning that into a new local working directory will get you back to what you started with originally.  Then copy the few files that have changed from your current working directory to the new one.  Commit the ones you want to push to epics-modules, i.e. not st.cmd which only has a new UNIQUE_ID or RELEASE files that are specific to your installation.

**Comment by MarkRivers** [comment]
Then push the new working directory to your new fork, and make a PR.

**Comment by MarkRivers** [comment]
> I'm an old CVS person. GIT for the most part is a mystery to me

I did CVS, then subversion, then git.  Git is really powerful and nice, but is a bit cryptic and hard to understand.

**Comment by David-Dudley** [comment]
so, normally, you always have files "uncommitted" in the git tree, related to those that you need to change for you're particular installation?

**Comment by David-Dudley** [comment]
I started in RCS or VCS or somthing like that.... seem to remember it had a much longer name than that????

many many moons ago.

**Comment by MarkRivers** [comment]
> so, normally, you always have files "uncommitted" in the git tree, related to those that you need to change for you're particular installation?

Yes.  We try to avoid having many files in the git repository that require local modification, but RELEASE and st.cmd often do need modification.  "git status" will show them as modified.

**Comment by anjohnson** [comment]
Hi David, I was going to suggest that you could avoid having to make changes to your local configure/RELEASE file by putting all your settings in a configure/RELEASE.local file instead because that should be ignored automatically, but Mark doesn't seem to have listed that in the .gitignore file for this module. You could instead put them in a RELEASE.local file in the directory _above_ your measComp working directory, but beware that if you have other modules checked out under the same parent directory they will probably include that file as well, so that's not an ideal solution either.

Mark, the Core developers recommend including the line
```gitignore
/configure/*.local
```
in the .gitignore file of any EPICS modules with configure/RELEASE and configure/CONFIG_SITE files that include equivalent `.local` versions of themselves from the `$(TOP)/configure` directory. Those particular include statements don't really provide any advantage without the matching ignore pattern.

**Comment by MarkRivers** [comment]
I've made Andrew's suggested change to .gitignore.

**Comment by MarkRivers** [comment]
@anjohnson I added
```
configure/*.local
```
Is that different from
```
/configure/*.local
```
i.e. does the leading / matter?

**Comment by anjohnson** [comment]
I thought it might matter, but the `git help gitignore` documentation says that it won't make any difference because the `/` is in the middle of the pattern. When the only `/` is at the end of a pattern though (e.g. `db/`) it will match any directories by that name in the tree — you have to use `/db/` to tell it to ignore only a top-level `db` directory for example. Personally it seems easier to always include the leading `/` for all top-level-only patterns than to try and remember the rules:
```
       o   The slash / is used as the directory separator. Separators may
           occur at the beginning, middle or end of the .gitignore search
           pattern.

       o   If there is a separator at the beginning or middle (or both) of the
           pattern, then the pattern is relative to the directory level of the
           particular .gitignore file itself. Otherwise the pattern may also
           match at any level below the .gitignore level.

       o   If there is a separator at the end of the pattern then the pattern
           will only match directories, otherwise the pattern can match both
           files and directories.

       o   For example, a pattern doc/frotz/ matches doc/frotz directory, but
           not a/doc/frotz directory; however frotz/ matches frotz and a/frotz
           that is a directory (all paths are relative from the .gitignore
           file).
```

**Comment by David-Dudley** [comment]
That’s what I’ve done.  I have a RELEASE.local in the parent directory. Several of the packages pick it up, but not every one has the  lines in the RELEASE file that pull it in.  I’ve added those lines in the ones that don’t pull it in.

That works great!

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Pull request closed without merging**
