### PR TITLE
Add USB-1608G to Linux Driver

### PR DESCRIPTION
**Pull request by David-Dudley**
2nd attempt.  Hopefully, this one works better.

### CODE REVIEW

**Comment by David-Dudley** [comment]
For some reason, I've already found something I'm going to have to fix.

Analog input channels above 2 seem to divide the provided voltage in half.  The WaveformDigitizer acquires the proper data on all channels, but the voltage you see on the display is different.

**Comment by MarkRivers** [comment]
> Analog input channels above 2 seem to divide the provided voltage in half. The WaveformDigitizer acquires the proper data on all channels, but the voltage you see on the display is different.

That is probably because EGUL and EGUF are not set correctly to match the range.  You need to open the analog input configuration screen.  We allow EGUL and EGUF to be set independently of the range, so that the user is not constrained to use voltage as the engineering unit.  They can use % of full scale, or a conversion to pressure, etc.

**Comment by David-Dudley** [comment]
That was it.

Curious.... does the waveform digitizer not go though the same conversions?

**Comment by MarkRivers** [comment]
> Curious.... does the waveform digitizer not go though the same conversions?

No.  Those conversions are not done in the driver, they are done in the ai record device support and in the record itself.  The waveform record device support does not have similar conversions, so it is constrained to using device units.  We could support conversion in the driver, but we would need a way to pass the conversion constants to the driver, which we don't currently do.  The conversion could also be done in an acalcout record in the database, without modifying the driver.

**Comment by David-Dudley** [comment]
hey, I'm happy.  Thing works, Warren has done the basic stuff to get the WaveformGenerator supported....

Lifes good.

**Comment by David-Dudley** [comment]
I have a utility file I created to use sed to change all the symbols in Warren's usb-1608 driver to what is needed in this repo.

I assume things like that don't go in the repo?  Seems like something that might be useful in the future...

**Review by MarkRivers — CHANGES_REQUESTED** [review]
It looks like you misspelled USB1608G_AIN_SCAN_RUNNNG (missing an I).

I prefer my version which has USB1608G_SINGLEIO rather than USB1608G_USB_SINGLEIO. Same for CONTINUOUS_READOUT and FORCE_PACKET_SIZE.

Line 126 in cbw_linux.cpp adds trailing whitespace.

**Review by MarkRivers — CHANGES_REQUESTED** [review]
mcBoard_1608G.h still has one tab character.

**Comment by MarkRivers** [comment]
> I have a utility file I created to use sed to change all the symbols in Warren's usb-1608 driver to what is needed in this repo.

That could go in the Linux_drivers repository to use an example for the future.

**Review by MarkRivers — APPROVED** [review]

**Pull request merged**
