### PR TITLE
Use only our own max channel number for TC32, to limit only one singl…

### PR DESCRIPTION
**Pull request by jeonghanlee**
Please check a simple proposal as follows.

https://github.com/epics-modules/measComp/issues/20

And let me know what you think.

### CODE REVIEW

**Review by MarkRivers — COMMENTED** [review]
I don't think this is the best solution.  I think increasing MAX_TEMPERATURE_IN to 64 is a better solution.

**Comment by jeonghanlee** [comment]
I reverted the change and changed `MAX_TEMPERATURE_IN` to 64.

**Comment by MarkRivers** [comment]
Are you able to test the change?  Does your TC-32 have 32 or 64 channels?

**Comment by jeonghanlee** [comment]
I have the 32 channels TC-32. I've tested it.

**Pull request merged**
