### PR TITLE
Fix compiler warnings

### PR DESCRIPTION
**Pull request by MarkRivers**
I made changes to 2 files to eliminate compiler warnings.

### CODE REVIEW

**Comment by MarkRivers** [comment]
@David-Dudley can you please look at this PR and see if you approve?  

It fixes problems with unused variables and functions, and uninitialized variables that result in compiler warnings.

**Review by David-Dudley — APPROVED** [review]
Looks good to me.

**Comment by David-Dudley** [comment]
whats the next step?

**Comment by MarkRivers** [comment]
If you were a member of this repository team you could merge the pull request.  Now that you have approved it I will merge it.

**Comment by MarkRivers** [comment]
Now you should update your fork to this latest version using the Github Web page, and then do "git pull" in your working directory to pull the changes from your updated fork.

**Comment by David-Dudley** [comment]
Stupid question...

How do I do that?  Is that just a “pull” back into my fork?

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Comment by David-Dudley** [comment]
Never mind… that’s just a “fetch upstream” from my fork?

David Dudley
Controls Engineer III
Facility for Rare Isotope Beams
Michigan State University
640 South Shaw Lane
East Lansing, MI 48824-1321, USA
Tel. 517-908-7133
Email: ***@***.******@***.***>



***@***.***

**Comment by David-Dudley** [comment]
Was just thinking...

My little note in the readme file about the Linux support should probably have been incorporated into the text at the area concerning the USB-1608

**Comment by MarkRivers** [comment]
Yes, the "fetch upstream" widget.

**Pull request merged**
